[project]
name = "technical-interview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "jinja2",
    "httpx",
    "pytest>=8.4.1",
]

[project.scripts]
fastapi = "cli:main"
